cargo-features = ["profile-rustflags"]

[package]
name = "mspm0l222x-hal"
version = "0.1.0"
authors = ["ctf@purdue.edu"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A Hardware Abstraction Layer for the Texas Instruments MSPM0L222X microcontroller family"
repository = "https://github.com/Purdue-eCTF/mspm0l222x-hal"
readme = "README.md"
keywords = ["mspm0l2228", "embedded-hal", "arm", "cortex-m"]
categories = ["embedded", "hardware-support", "no-std", "no-std::no-alloc"]

[package.metadata.docs.rs]
targets = ["thumbv6m-none-eabi"]

[dependencies]
bytemuck = "1.24.0"
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
mspm0l222x-pac = { path = "../mspm0l222x-pac" }
once_cell = { version = "1.21.3", default-features = false, features = [
    "critical-section",
] }
thiserror = { version = "2.0.17", default-features = false }

[features]
default = ["rt"]
rt = ["mspm0l222x-pac/critical-section", "mspm0l222x-pac/rt"]

[profile.dev.package.mspm0l222x-pac]
rustflags = ["-Zhint-mostly-unused"]


[profile.release.package.mspm0l222x-pac]
rustflags = ["-Zhint-mostly-unused"]
