[build]
target = "thumbv6m-none-eabi"

[unstable]
profile-rustflags = true


[target.thumbv6m-none-eabi]
rustflags = [
    "-C",
    "linker=arm-none-eabi-gcc",
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-Tlink.x",
    # "-C",
    # "link-arg=--verbose"
]
runner = ["sh", "run.sh"]